// DOCX → DocModel (P007/P010). The real fixture test-fixtures/sample.docx is a
// genuine OOXML Word file generated by scripts/generate_docx_fixture.mjs.
//
// mammoth's node build is used in the test to turn the fixture into HTML; the
// app uses the browser build. Both feed the same pure htmlToDocModel.

import { readFileSync } from 'fs';
import { join } from 'path';
import { describe, it, expect } from 'vitest';
import mammoth from 'mammoth';
import { htmlToDocModel } from '@/lib/docxToDocModel';

describe('htmlToDocModel (pure mapping)', () => {
  it('maps h1–h6 → headings, p → paragraphs, li → list items, in order', () => {
    const html = '<h1>Title</h1><p>Intro.</p><h2>Sub</h2><ul><li>one</li><li>two</li></ul><p>End &amp; done.</p>';
    const { blocks } = htmlToDocModel(html);
    expect(blocks).toEqual([
      { type: 'heading', level: 1, text: 'Title', page: 1 },
      { type: 'paragraph', text: 'Intro.', page: 1 },
      { type: 'heading', level: 2, text: 'Sub', page: 1 },
      { type: 'listItem', text: 'one', page: 1 },
      { type: 'listItem', text: 'two', page: 1 },
      { type: 'paragraph', text: 'End & done.', page: 1 }, // entity decoded
    ]);
  });
});

describe('DOCX → DocModel (sample.docx)', () => {
  it('preserves Word heading styles as headings (not flattened to paragraphs)', async () => {
    const bytes = readFileSync(join(process.cwd(), 'test-fixtures', 'sample.docx'));
    const { value: html } = await mammoth.convertToHtml({ buffer: bytes });
    const { blocks } = htmlToDocModel(html);

    // Heading 1 / Heading 2 Word styles survive as real headings.
    expect(blocks).toContainEqual({ type: 'heading', level: 1, text: 'Quarterly Report', page: 1 });
    expect(blocks).toContainEqual({ type: 'heading', level: 2, text: 'Overview', page: 1 });
    expect(blocks).toContainEqual({ type: 'heading', level: 1, text: 'Financials', page: 1 });
    // Body text is present as paragraphs.
    expect(blocks).toContainEqual({ type: 'paragraph', text: 'This is the introduction paragraph of the report.', page: 1 });
  });
});
